import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
import { Inter, Rubik } from "next/font/google";
import Header from "@/components/TheHeader";
import Footer from "@/components/TheFooter";
import { cookies } from "next/headers";
import { PermissionContextProvider } from "@/Store/permission-context";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: {
    absolute: "EAUED MHS",
    template: "EAUED MHS | %s",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const Cookies = new cookies();
  const cat = Cookies.get("Category") ? Cookies.get("Category").value : "";
  const Category = cat === "Admin" ? true : false;

  return (
    <html lang="en">
      <body className={inter.className}>
        <PermissionContextProvider>
          <Header Category={Category} />
          {children}
          <Footer />
        </PermissionContextProvider>
      </body>
    </html>
  );
}
